// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Model;

public partial class brand
{
    public int BrandID { get; set; }

    public string BrandName { get; set; }

    public virtual ICollection<shoesmodel> shoesmodel { get; } = new List<shoesmodel>();
}