// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Model;

public partial class customer
{
    public int CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string HashPassword { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public int? AccountStatus { get; set; }

    public virtual ICollection<cartdetail> cartdetail { get; } = new List<cartdetail>();

    public virtual ICollection<purchaseorder> purchaseorder { get; } = new List<purchaseorder>();

    public virtual ICollection<rate> rate { get; } = new List<rate>();
}