// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Model;

public partial class orderdetail
{
    public int PurchaseOrderID { get; set; }

    public int ShoesID { get; set; }

    public int UnitPrice { get; set; }

    public int Quantity { get; set; }

    public virtual purchaseorder PurchaseOrder { get; set; }

    public virtual shoes Shoes { get; set; }
}