// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Model;

public partial class shoes
{
    public int ShoesID { get; set; }

    public int ShoesModelID { get; set; }

    public string Color { get; set; }

    public int? Size { get; set; }

    public int UnitPrice { get; set; }

    public int Quantity { get; set; }

    public int? ShoesStatus { get; set; }

    public virtual shoesmodel ShoesModel { get; set; }

    public virtual ICollection<cartdetail> cartdetail { get; } = new List<cartdetail>();

    public virtual ICollection<orderdetail> orderdetail { get; } = new List<orderdetail>();
}