// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Model;

public partial class store
{
    public int StoreID { get; set; }

    public string StoreName { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }
}