// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Models;

public partial class purchaseorder
{
    public int PurchaseOrderID { get; set; }

    public int CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateTime OrderTime { get; set; }

    public string Address { get; set; }

    public int OrderStatus { get; set; }

    public string Note { get; set; }

    public virtual customer Customer { get; set; }

    public virtual ICollection<orderdetail> orderdetail { get; } = new List<orderdetail>();
}