// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Models;

public partial class rate
{
    public int PurchaseOrderID { get; set; }

    public int ShoesID { get; set; }

    public int CustomerID { get; set; }

    public int RateStar { get; set; }

    public string Content { get; set; }

    public DateTime RateTime { get; set; }

    public string ImageLink { get; set; }

    public virtual customer Customer { get; set; }

    public virtual orderdetail orderdetail { get; set; }
}