// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Models;

public partial class shoesmodel
{
    public int ShoesModelID { get; set; }

    public string ShoesModelName { get; set; }

    public int BrandID { get; set; }

    public string ShoesModelDescription { get; set; }

    public int? ShoesModelStatus { get; set; }

    public virtual brand Brand { get; set; }

    public virtual ICollection<rate> rate { get; } = new List<rate>();

    public virtual ICollection<shoes> shoes { get; } = new List<shoes>();

    public virtual ICollection<shoesmodelimage> shoesmodelimage { get; } = new List<shoesmodelimage>();
}