// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheShoesShop_BackEnd.Models;

public partial class storeadmin
{
    public int StoreAdminID { get; set; }

    public string HashPassword { get; set; }

    public string Email { get; set; }
}